### ISSUE TITLE
Noob issue with ...

### ISSUE THREAD

**Issue by Charost** [espressif/arduino-esp32#3462]
Hii guy could someone help me ? 
I am new user of esp32  and i always have the following error whenver I upload the code on esp32 board .
```
esptool.py v2.6 Serial port COM3 Connecting... 
Traceback (most recent call last):   
File "esptool.py", line 2959, in <module>   
File "esptool.py", line 2952, in _main   
File "esptool.py", line 2653, in main   
File "esptool.py", line 460, in connect   
File "esptool.py", line 440, in _connect_attempt   
File "esptool.py", line 379, in sync   
File "esptool.py", line 322, in command   
File "esptool.py", line 285, in write   
File "site-packages\serial\serialwin32.py", line 323, in write serial.serialutil.
SerialTimeoutException: Write timeout 
Failed to execute script esptool Une erreur est survenue lors du transfert du croquis

Failed to execute script esptool An error occurred while uploading the sketch (Google Translate)
```

**Comment by lbernstone** [comment]
Please fix your title.  It should be one line.
https://github.com/espressif/arduino-esp32/issues/333#issuecomment-303476651

**Comment by mrdc** [comment]
@Charost 
Try to use Google first. It's not arduino-esp32 or Arduino IDE issue.

@lbernstone 

I think he should be banned for this.

**Comment by me-no-dev** [comment]
ban is a bit harsh, no?

@Charost the actual error is on the next line that you did not paste... can's help much here

**Comment by Azkarehman** [comment]
Im facing same issue :) 

Arduino: 1.8.13 (Windows Store 1.8.42.0) (Windows 10), Board: "AI Thinker ESP32-CAM"

Sketch uses 2100647 bytes (66%) of program storage space. Maximum is 3145728 bytes.

Global variables use 53552 bytes (16%) of dynamic memory, leaving 274128 bytes for local variables. Maximum is 327680 bytes.

esptool.py v2.6

Serial port COM4

Connecting.....

Traceback (most recent call last):

  File "esptool.py", line 2959, in <module>

  File "esptool.py", line 2952, in _main

  File "esptool.py", line 2653, in main

  File "esptool.py", line 460, in connect

  File "esptool.py", line 440, in _connect_attempt

  File "esptool.py", line 379, in sync

  File "esptool.py", line 322, in command

  File "esptool.py", line 285, in write

  File "site-packages\serial\serialwin32.py", line 323, in write

serial.serialutil.SerialTimeoutException: Write timeout

Failed to execute script esptool

An error occurred while uploading the sketch



This report would have more information with
"Show verbose output during compilation"
option enabled in File -> Preferences.
