### ISSUE TITLE
ESP32 boards error on upload

### ISSUE THREAD

**Issue by aiotech-pub** [espressif/arduino-esp32#5936]
I have a Wemos D1 R32 board that is compatible with EspDuino32. Using Arduino ide I am able to build the applications but I am not able to upload/program the board.
This is the error:
java.lang.NullPointerException
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingProgrammer(SerialUploader.java:295)
	at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:90)
	at cc.arduino.UploaderUtils.upload(UploaderUtils.java:77)
	at processing.app.SketchController.upload(SketchController.java:732)
	at processing.app.SketchController.exportApplet(SketchController.java:703)
	at processing.app.Editor$UploadHandler.run(Editor.java:2055)
	at java.lang.Thread.run(Thread.java:748)
The same problem arises also using the Sloeber plugin on Eclipse.
This is the returned error:
upload failed for "L/BlinkESP32/BlinkESP32}/Release/BlinkESP32.hex"
esptool
tools.esptool.upload.pattern : not found in the platform.txt file

I tryed to change the board to see if something changes and I discovered that produces the same or other errors mainly related to the esptool (wrong parameters or not found). Instead, generally, there are no probolems to build the application.

**Comment by VojtechBartoska** [comment]
Hello. sorry for answering you late. Do you still need help?

**Comment by VojtechBartoska** [comment]
Hello,

as there was no answer in more than 14 days, I'm closing the issue as expired to keep our backlog manageable.

If it's still needed, please reopen the issue.

Thanks for understanding.
