### ISSUE TITLE
To add function to get current FS operation mode (READ, WRITE, APPEND)

### ISSUE THREAD

**Issue by tsctrl** [espressif/arduino-esp32#8047]
### Related area

FS library support

### Hardware specification

ESP32 DevKit

### Is your feature request related to a problem?

hi @me-no-dev @SuGlider 

from the below error it was suggested from the maintainer of little fs library that this is issue caused by reading a file that was on write only mode. or possible because of concurrency issue.

```
#0  0x40081a49 in panic_abort (details=0x3ffd7034 \"assert failed: lfs_file_rawwrite lfs.c:3415 ((file->flags & LFS_O_WRONLY) == LFS_O_WRONLY)\") at C:/Desp-idf-v4.4.1/components/esp_system/panic.c:402
#1  0x40088eb4 in esp_system_abort (details=0x3ffd7034 \"assert failed: lfs_file_rawwrite lfs.c:3415 ((file->flags & LFS_O_WRONLY) == LFS_O_WRONLY)\") at C:/esp-idf-v4.4.1/components/esp_system/esp_system.c:128
Backtrace stopped: previous frame identical to this frame (corrupt stack?)
```
as here: https://github.com/joltwallet/esp_littlefs/issues/116

this was caused by a write que task implementation that runs continuously to write a logs to file and race with other file read operation on the main taks. i could not resolve or figureout the cause for this and had more than months of required time to investigate. is it possible to have workaround on my que to skip writing to the FS if the file open mode is not match which could stop system panic and restart.

### Describe the solution you'd like

it it possible to have a function in FS to get current FS mode? if this implemented, 

1. will this be a breaking changes for all compatible file format that currently supported 
2. will this implementation require this to be implemented by the library (in this case LittleFS) to have this new function to work 
3.or is it can be done in FS class only?

do you have suggestion any workaround on this, even though LittleFS has mutex but i am still getting the race/concurrency issue on the FS and currently i have to use my own mutexes control to the FS to que the rtos tasks to read the FS!

Your kind reply and suggestion are highly appreciated. Thanks!

### I have checked existing list of Feature requests and the Contribution Guide

- [X] I confirm I have checked existing list of Feature requests and Contribution Guide.

**Comment by tsctrl** [comment]
i have check and to know that all fs impl library will also have to support the same request implementation for this  which was not viable for the case, closing this request which was not directly feasible.

thanks!
